**Transformers = Probabilistic Encoding and Deterministic Decoding**

**HDC = Deterministic Encoding and Probabilistic Decoding**

**Standard Word Vectorization:**

In [ ]:
from gensim.models import Word2Vec
import numpy as np

# Example sentence
sentence = "The cat sat on the mat"

# Manually tokenize the sentence
tokens = sentence.lower().split()

# Prepare data for Word2Vec
sentences = [tokens]  # Word2Vec expects a list of tokenized sentences

# Train a Word2Vec model
model = Word2Vec(sentences, vector_size=10, window=5, min_count=1, sg=0)

# Get word vectors for each word in the sentence
word_vectors = {word: model.wv[word] for word in tokens}

# Aggregate the vectors to encode the entire sentence (e.g., by averaging)
sentence_vector = np.mean([model.wv[word] for word in tokens], axis=0)

# Display the word vectors and the final sentence vector
word_vectors, sentence_vector

({'the': array([-0.00536227,  0.00236431,  0.0510335 ,  0.09009273, -0.0930295 ,
         -0.07116809,  0.06458873,  0.08972988, -0.05015428, -0.03763372],
        dtype=float32),
  'cat': array([-0.0960355 ,  0.05007293, -0.08759586, -0.04391825, -0.000351  ,
         -0.00296181, -0.0766124 ,  0.09614743,  0.04982058,  0.09233143],
        dtype=float32),
  'sat': array([-0.07511582, -0.00930042,  0.09538119, -0.07319167, -0.02333769,
         -0.01937741,  0.08077437, -0.05930896,  0.00045162, -0.04753734],
        dtype=float32),
  'on': array([ 0.07311766,  0.05070262,  0.06757693,  0.00762866,  0.06350891,
         -0.03405366, -0.00946401,  0.05768573, -0.07521638, -0.03936104],
        dtype=float32),
  'mat': array([ 0.07380505, -0.01533471, -0.04536613,  0.06554051, -0.0486016 ,
         -0.01816018,  0.0287658 ,  0.00991874, -0.08285215, -0.09448818],
        dtype=float32)},
 array([-0.00582553,  0.01347817,  0.02201052,  0.02270745, -0.0324734 ,
        -0.03614821,  0.025

**Hypervector Encoding:**

In [ ]:
import numpy as np

# Example sentence
sentence = "The cat sat on the mat"

# Manually tokenize the sentence
tokens = sentence.lower().split()

# Define a high-dimensional space (e.g., 10,000 dimensions)
dimension = 10000

# Initialize random seed for reproducibility
np.random.seed(42)

# Create random hypervectors for each unique token
unique_tokens = set(tokens)
hypervectors = {token: np.random.choice([-1, 1], size=dimension) for token in unique_tokens}

# Encode the sentence by bundling the hypervectors of its tokens
# Bundling is typically summation followed by binarization (sign function)
sentence_hypervector = np.sum([hypervectors[token] for token in tokens], axis=0)
sentence_hypervector = np.sign(sentence_hypervector)  # Binarize to -1/+1

# Display the hypervectors for each word and the final encoded sentence vector
hypervectors, sentence_hypervector

({'sat': array([-1,  1, -1, ...,  1,  1, -1]),
  'cat': array([-1,  1, -1, ..., -1,  1, -1]),
  'the': array([-1,  1,  1, ...,  1,  1, -1]),
  'on': array([ 1,  1, -1, ..., -1,  1,  1]),
  'mat': array([ 1,  1,  1, ..., -1,  1, -1])},
 array([-1,  1,  0, ...,  0,  1, -1]))

The mathematical differences between **Word2Vec encoding** and **Hyperdimensional Computing (HDC) encoding** stem from their distinct design philosophies, mathematical operations, and goals. Here's a detailed breakdown:

---

### **1. Representation of Words**
#### **Word2Vec:**
- Represents words as **dense, low-dimensional vectors** (e.g., 100-300 dimensions).
- Vectors are learned during training and optimized to capture semantic relationships through co-occurrence or prediction tasks.
- The vectors are **continuous-valued**, meaning each dimension contains real numbers that reflect learned features.

#### **HDC:**
- Represents words as **high-dimensional binary vectors** (e.g., 10,000+ dimensions).
- Hypervectors are typically **randomly generated** (e.g., -1 or +1) to ensure they are nearly orthogonal.
- Encoding leverages properties like distributed representation, where information is spread across many dimensions.

---

### **2. Encoding Process**
#### **Word2Vec:**
- **Training**:
  - Uses optimization techniques to learn word vectors by minimizing a loss function.
    - **Skip-Gram**: Predicts surrounding words given a target word.
    - **CBOW (Continuous Bag of Words)**: Predicts the target word given surrounding words.
  - Captures **contextual relationships** through dot products or cosine similarities between word vectors.
- **Mathematical Operation**:
  - **Dot product** is used to calculate similarities during training.
  - The embeddings emerge from iterative updates to minimize prediction errors.

#### **HDC:**
- **Binding and Bundling**:
  - **Binding** (e.g., XOR or element-wise multiplication): Encodes relationships between data points (e.g., associating features with a word).
  - **Bundling** (e.g., summation and sign function): Combines multiple vectors into a single composite vector.
- **Mathematical Operation**:
  - No learning; the process is deterministic.
  - Summation aggregates information, while **binarization** (via the sign function) ensures hypervectors remain in the -1/+1 space.
  
---

### **3. Dimensionality**
#### **Word2Vec**:
- **Low-dimensional space** (e.g., 100-300 dimensions).
- Each dimension captures a specific learned feature of the data.

#### **HDC**:
- **High-dimensional space** (e.g., 10,000+ dimensions).
- Exploits the properties of high-dimensional spaces, like near-orthogonality and robustness to noise.

---

### **4. Similarity Computation**
#### **Word2Vec**:
- Semantic similarity is measured using **cosine similarity**:
  \[
  \text{Similarity} = \frac{\vec{v_1} \cdot \vec{v_2}}{\|\vec{v_1}\| \|\vec{v_2}\|}
  \]
- Focuses on finding relationships between vectors based on their orientation in the embedding space.

#### **HDC**:
- Similarity is also measured using **cosine similarity**:
  \[
  \text{Similarity} = \frac{\vec{h_1} \cdot \vec{h_2}}{\|\vec{h_1}\| \|\vec{h_2}\|}
  \]
- However, hypervectors are binary (-1/+1) and randomly generated, so their similarity arises from the properties of high-dimensional spaces rather than learned relationships.

---

### **5. Learning vs. Deterministic Encoding**
#### **Word2Vec**:
- Encoding is the **result of learning**:
  - Vectors are trained to optimize specific objectives, reflecting semantic and syntactic relationships.
  - The encoding evolves through iterative updates based on the training data.

#### **HDC**:
- Encoding is **deterministic**:
  - Hypervectors are generated randomly and combined through mathematical operations.
  - No training or optimization occurs; the encoding is based on distributed representation and compositionality.

---

### **6. Noise Robustness**
#### **Word2Vec**:
- Sensitive to training data. Poor or insufficient data can lead to suboptimal embeddings.
- Not inherently robust to noise unless additional preprocessing or techniques are applied.

#### **HDC**:
- Highly robust to noise due to the redundancy of high-dimensional binary spaces.
- Small errors in individual dimensions have minimal impact on the overall encoding.

---

### **Summary of Key Differences**

| Aspect                  | **Word2Vec**                                   | **HDC**                                      |
|-------------------------|-----------------------------------------------|---------------------------------------------|
| **Mathematics**         | Optimized embeddings via dot products and loss minimization. | Deterministic operations: summation, XOR, sign. |
| **Dimensionality**      | Low-dimensional (100–300).                    | High-dimensional (10,000+).                 |
| **Data Representation** | Continuous real-valued vectors.               | Binary (-1/+1) vectors.                     |
| **Learning**            | Trained on data using objectives like Skip-Gram or CBOW. | No training; encodings are predefined.      |
| **Similarity**          | Cosine similarity based on learned features.  | Cosine similarity based on high-dimensional structure. |
| **Robustness**          | Sensitive to training data and noise.         | Inherently robust to noise.                 |

Both Word2Vec and HDC are powerful in their domains, but Word2Vec shines in capturing semantic relationships through learned embeddings, while HDC excels in robustness and compositionality with deterministic encodings.

In [ ]:
import numpy as np

# Example paragraph
paragraph = """
The cat sat on the mat. It was a sunny day, and the cat enjoyed basking in the warm sunlight.
"""

# Tokenize the paragraph into words
tokens = paragraph.lower().replace(".", "").replace(",", "").split()

# Define high-dimensional space (e.g., 10,000 dimensions)
dimension = 10000

# Initialize random seed for reproducibility
np.random.seed(42)

# Create random hypervectors for each unique token
unique_tokens = set(tokens)
hypervectors = {token: np.random.choice([-1, 1], size=dimension) for token in unique_tokens}

# Encode the paragraph by bundling the hypervectors of its tokens
# Bundling: summation followed by binarization (sign function)
paragraph_hypervector = np.sum([hypervectors[token] for token in tokens], axis=0)
paragraph_hypervector = np.sign(paragraph_hypervector)  # Binarize to -1/+1

# Output the hypervectors for each unique word and the encoded paragraph vector
hypervectors, paragraph_hypervector


({'sat': array([-1,  1, -1, ...,  1,  1, -1]),
  'cat': array([-1,  1, -1, ..., -1,  1, -1]),
  'was': array([-1,  1,  1, ...,  1,  1, -1]),
  'the': array([ 1,  1, -1, ..., -1,  1,  1]),
  'a': array([ 1,  1,  1, ..., -1,  1, -1]),
  'and': array([ 1,  1,  1, ...,  1, -1, -1]),
  'on': array([-1, -1,  1, ...,  1, -1, -1]),
  'it': array([-1,  1,  1, ..., -1, -1, -1]),
  'day': array([ 1, -1, -1, ...,  1, -1,  1]),
  'basking': array([ 1,  1, -1, ..., -1,  1,  1]),
  'enjoyed': array([-1,  1,  1, ...,  1,  1, -1]),
  'sunlight': array([-1,  1, -1, ..., -1, -1,  1]),
  'sunny': array([ 1, -1, -1, ...,  1,  1,  1]),
  'in': array([-1,  1,  1, ..., -1,  1,  1]),
  'mat': array([ 1, -1, -1, ...,  1,  1,  1]),
  'warm': array([-1,  1,  1, ...,  1,  1,  1])},
 array([ 0,  1, -1, ..., -1,  1,  1]))

### **Details:**
1. **Hypervectors for Words:**
   - Each unique word (e.g., `"cat"`, `"sunlight"`, `"basking"`) is assigned a randomly generated **hypervector** of 10,000 dimensions, filled with `-1` and `+1`.
   - Example: `"cat"` → `[ -1, 1, 1, ..., 1, 1, -1 ]`

2. **Paragraph Encoding:**
   - The paragraph is encoded by **bundling** all word hypervectors together:
     - Summing the hypervectors for all words in the paragraph.
     - Applying the **sign function** to binarize the summed vector, ensuring it remains in the space of `-1` and `+1`.
   - The resulting **paragraph hypervector** is a single high-dimensional vector that holistically represents the entire text.

---

### **Output:**
1. A dictionary of hypervectors for each unique word in the paragraph.
2. A **single high-dimensional binary vector** that encodes the paragraph.

**Transformers = Probabilistic Encoding and Deterministic Decoding**

**HDC = Deterministic Encoding and Probabilistic Decoding**

**Standard Word Vectorization:**

In [ ]:
from gensim.models import Word2Vec
import numpy as np

# Example sentence
sentence = "The cat sat on the mat"

# Manually tokenize the sentence
tokens = sentence.lower().split()

# Prepare data for Word2Vec
sentences = [tokens]  # Word2Vec expects a list of tokenized sentences

# Train a Word2Vec model
model = Word2Vec(sentences, vector_size=10, window=5, min_count=1, sg=0)

# Get word vectors for each word in the sentence
word_vectors = {word: model.wv[word] for word in tokens}

# Aggregate the vectors to encode the entire sentence (e.g., by averaging)
sentence_vector = np.mean([model.wv[word] for word in tokens], axis=0)

# Display the word vectors and the final sentence vector
word_vectors, sentence_vector

({'the': array([-0.00536227,  0.00236431,  0.0510335 ,  0.09009273, -0.0930295 ,
         -0.07116809,  0.06458873,  0.08972988, -0.05015428, -0.03763372],
        dtype=float32),
  'cat': array([-0.0960355 ,  0.05007293, -0.08759586, -0.04391825, -0.000351  ,
         -0.00296181, -0.0766124 ,  0.09614743,  0.04982058,  0.09233143],
        dtype=float32),
  'sat': array([-0.07511582, -0.00930042,  0.09538119, -0.07319167, -0.02333769,
         -0.01937741,  0.08077437, -0.05930896,  0.00045162, -0.04753734],
        dtype=float32),
  'on': array([ 0.07311766,  0.05070262,  0.06757693,  0.00762866,  0.06350891,
         -0.03405366, -0.00946401,  0.05768573, -0.07521638, -0.03936104],
        dtype=float32),
  'mat': array([ 0.07380505, -0.01533471, -0.04536613,  0.06554051, -0.0486016 ,
         -0.01816018,  0.0287658 ,  0.00991874, -0.08285215, -0.09448818],
        dtype=float32)},
 array([-0.00582553,  0.01347817,  0.02201052,  0.02270745, -0.0324734 ,
        -0.03614821,  0.025

**Hypervector Encoding:**

In [ ]:
import numpy as np

# Example sentence
sentence = "The cat sat on the mat"

# Manually tokenize the sentence
tokens = sentence.lower().split()

# Define a high-dimensional space (e.g., 10,000 dimensions)
dimension = 10000

# Initialize random seed for reproducibility
np.random.seed(42)

# Create random hypervectors for each unique token
unique_tokens = set(tokens)
hypervectors = {token: np.random.choice([-1, 1], size=dimension) for token in unique_tokens}

# Encode the sentence by bundling the hypervectors of its tokens
# Bundling is typically summation followed by binarization (sign function)
sentence_hypervector = np.sum([hypervectors[token] for token in tokens], axis=0)
sentence_hypervector = np.sign(sentence_hypervector)  # Binarize to -1/+1

# Display the hypervectors for each word and the final encoded sentence vector
hypervectors, sentence_hypervector

({'sat': array([-1,  1, -1, ...,  1,  1, -1]),
  'cat': array([-1,  1, -1, ..., -1,  1, -1]),
  'the': array([-1,  1,  1, ...,  1,  1, -1]),
  'on': array([ 1,  1, -1, ..., -1,  1,  1]),
  'mat': array([ 1,  1,  1, ..., -1,  1, -1])},
 array([-1,  1,  0, ...,  0,  1, -1]))

The mathematical differences between **Word2Vec encoding** and **Hyperdimensional Computing (HDC) encoding** stem from their distinct design philosophies, mathematical operations, and goals. Here's a detailed breakdown:

---

### **1. Representation of Words**
#### **Word2Vec:**
- Represents words as **dense, low-dimensional vectors** (e.g., 100-300 dimensions).
- Vectors are learned during training and optimized to capture semantic relationships through co-occurrence or prediction tasks.
- The vectors are **continuous-valued**, meaning each dimension contains real numbers that reflect learned features.

#### **HDC:**
- Represents words as **high-dimensional binary vectors** (e.g., 10,000+ dimensions).
- Hypervectors are typically **randomly generated** (e.g., -1 or +1) to ensure they are nearly orthogonal.
- Encoding leverages properties like distributed representation, where information is spread across many dimensions.

---

### **2. Encoding Process**
#### **Word2Vec:**
- **Training**:
  - Uses optimization techniques to learn word vectors by minimizing a loss function.
    - **Skip-Gram**: Predicts surrounding words given a target word.
    - **CBOW (Continuous Bag of Words)**: Predicts the target word given surrounding words.
  - Captures **contextual relationships** through dot products or cosine similarities between word vectors.
- **Mathematical Operation**:
  - **Dot product** is used to calculate similarities during training.
  - The embeddings emerge from iterative updates to minimize prediction errors.

#### **HDC:**
- **Binding and Bundling**:
  - **Binding** (e.g., XOR or element-wise multiplication): Encodes relationships between data points (e.g., associating features with a word).
  - **Bundling** (e.g., summation and sign function): Combines multiple vectors into a single composite vector.
- **Mathematical Operation**:
  - No learning; the process is deterministic.
  - Summation aggregates information, while **binarization** (via the sign function) ensures hypervectors remain in the -1/+1 space.
  
---

### **3. Dimensionality**
#### **Word2Vec**:
- **Low-dimensional space** (e.g., 100-300 dimensions).
- Each dimension captures a specific learned feature of the data.

#### **HDC**:
- **High-dimensional space** (e.g., 10,000+ dimensions).
- Exploits the properties of high-dimensional spaces, like near-orthogonality and robustness to noise.

---

### **4. Similarity Computation**
#### **Word2Vec**:
- Semantic similarity is measured using **cosine similarity**:
  \[
  \text{Similarity} = \frac{\vec{v_1} \cdot \vec{v_2}}{\|\vec{v_1}\| \|\vec{v_2}\|}
  \]
- Focuses on finding relationships between vectors based on their orientation in the embedding space.

#### **HDC**:
- Similarity is also measured using **cosine similarity**:
  \[
  \text{Similarity} = \frac{\vec{h_1} \cdot \vec{h_2}}{\|\vec{h_1}\| \|\vec{h_2}\|}
  \]
- However, hypervectors are binary (-1/+1) and randomly generated, so their similarity arises from the properties of high-dimensional spaces rather than learned relationships.

---

### **5. Learning vs. Deterministic Encoding**
#### **Word2Vec**:
- Encoding is the **result of learning**:
  - Vectors are trained to optimize specific objectives, reflecting semantic and syntactic relationships.
  - The encoding evolves through iterative updates based on the training data.

#### **HDC**:
- Encoding is **deterministic**:
  - Hypervectors are generated randomly and combined through mathematical operations.
  - No training or optimization occurs; the encoding is based on distributed representation and compositionality.

---

### **6. Noise Robustness**
#### **Word2Vec**:
- Sensitive to training data. Poor or insufficient data can lead to suboptimal embeddings.
- Not inherently robust to noise unless additional preprocessing or techniques are applied.

#### **HDC**:
- Highly robust to noise due to the redundancy of high-dimensional binary spaces.
- Small errors in individual dimensions have minimal impact on the overall encoding.

---

### **Summary of Key Differences**

| Aspect                  | **Word2Vec**                                   | **HDC**                                      |
|-------------------------|-----------------------------------------------|---------------------------------------------|
| **Mathematics**         | Optimized embeddings via dot products and loss minimization. | Deterministic operations: summation, XOR, sign. |
| **Dimensionality**      | Low-dimensional (100–300).                    | High-dimensional (10,000+).                 |
| **Data Representation** | Continuous real-valued vectors.               | Binary (-1/+1) vectors.                     |
| **Learning**            | Trained on data using objectives like Skip-Gram or CBOW. | No training; encodings are predefined.      |
| **Similarity**          | Cosine similarity based on learned features.  | Cosine similarity based on high-dimensional structure. |
| **Robustness**          | Sensitive to training data and noise.         | Inherently robust to noise.                 |

Both Word2Vec and HDC are powerful in their domains, but Word2Vec shines in capturing semantic relationships through learned embeddings, while HDC excels in robustness and compositionality with deterministic encodings.

In [ ]:
import numpy as np

# Example paragraph
paragraph = """
The cat sat on the mat. It was a sunny day, and the cat enjoyed basking in the warm sunlight.
"""

# Tokenize the paragraph into words
tokens = paragraph.lower().replace(".", "").replace(",", "").split()

# Define high-dimensional space (e.g., 10,000 dimensions)
dimension = 10000

# Initialize random seed for reproducibility
np.random.seed(42)

# Create random hypervectors for each unique token
unique_tokens = set(tokens)
hypervectors = {token: np.random.choice([-1, 1], size=dimension) for token in unique_tokens}

# Encode the paragraph by bundling the hypervectors of its tokens
# Bundling: summation followed by binarization (sign function)
paragraph_hypervector = np.sum([hypervectors[token] for token in tokens], axis=0)
paragraph_hypervector = np.sign(paragraph_hypervector)  # Binarize to -1/+1

# Output the hypervectors for each unique word and the encoded paragraph vector
hypervectors, paragraph_hypervector


({'sat': array([-1,  1, -1, ...,  1,  1, -1]),
  'cat': array([-1,  1, -1, ..., -1,  1, -1]),
  'was': array([-1,  1,  1, ...,  1,  1, -1]),
  'the': array([ 1,  1, -1, ..., -1,  1,  1]),
  'a': array([ 1,  1,  1, ..., -1,  1, -1]),
  'and': array([ 1,  1,  1, ...,  1, -1, -1]),
  'on': array([-1, -1,  1, ...,  1, -1, -1]),
  'it': array([-1,  1,  1, ..., -1, -1, -1]),
  'day': array([ 1, -1, -1, ...,  1, -1,  1]),
  'basking': array([ 1,  1, -1, ..., -1,  1,  1]),
  'enjoyed': array([-1,  1,  1, ...,  1,  1, -1]),
  'sunlight': array([-1,  1, -1, ..., -1, -1,  1]),
  'sunny': array([ 1, -1, -1, ...,  1,  1,  1]),
  'in': array([-1,  1,  1, ..., -1,  1,  1]),
  'mat': array([ 1, -1, -1, ...,  1,  1,  1]),
  'warm': array([-1,  1,  1, ...,  1,  1,  1])},
 array([ 0,  1, -1, ..., -1,  1,  1]))

### **Details:**
1. **Hypervectors for Words:**
   - Each unique word (e.g., `"cat"`, `"sunlight"`, `"basking"`) is assigned a randomly generated **hypervector** of 10,000 dimensions, filled with `-1` and `+1`.
   - Example: `"cat"` → `[ -1, 1, 1, ..., 1, 1, -1 ]`

2. **Paragraph Encoding:**
   - The paragraph is encoded by **bundling** all word hypervectors together:
     - Summing the hypervectors for all words in the paragraph.
     - Applying the **sign function** to binarize the summed vector, ensuring it remains in the space of `-1` and `+1`.
   - The resulting **paragraph hypervector** is a single high-dimensional vector that holistically represents the entire text.

---

### **Output:**
1. A dictionary of hypervectors for each unique word in the paragraph.
2. A **single high-dimensional binary vector** that encodes the paragraph.